HW bash architecture
Atos1337/SD-Homeworks pull request #1
Opened 2022-01-23 17:49 UTC by turovkv

2022-01-23 19:02 UTC, yurii-litvinov requested changes
Общий комментарий по диаграмме: часть условия про "это не должен быть просто клубок классов, требуется некая компонентная структура" полностью провалена :) Оно выглядит уж совсем хаотично. Впрочем, мы ещё про диаграммы поговорим, так что сейчас и так сойдёт (разве что немного причесать надо, чтобы стрелки уж совсем из середины класса не начинались, как в случае с Parser, и расположите классы как-то более аккуратно). И, на будущее, стрелка наследования в UML указывает на предка, а не на потомка (ну, и extends на ней не пишется, но разные редакторы могут иметь своё мнение на этот счёт).

Но в целом всё очень неплохо. Кажется, обо всём подумали.

2022-01-23 19:49 UTC, Atos1337 commented on bash-cli/ARCHITECTURE.md
> +    *   Далее создаём файлы `.cli_input`, `.cli_output`
То есть можно считать, что у нас все промежуточные результаты вмещаются в оперативку, раз можно писать в байтовый массив?

2022-01-23 19:52 UTC, Atos1337 commented on bash-cli/ARCHITECTURE.md
> +* не в кавычках
Для такого случая:
```bash
x=1
"x=1"
```
В первом случае команда присваивания, во втором "x=1" command not found, а оператор присваивания мы определяем по наличию `=` в токене, поэтому ещё нужна информация о кавычках.

2022-01-25 14:32 UTC, yurii-litvinov commented on bash-cli/ARCHITECTURE.md
> +    *   Далее создаём файлы `.cli_input`, `.cli_output`
Да, думаю да, хотя это тоже архитектурное решение. Если результаты таки не влезут, шелл может упасть, зато на небольших промежуточных результатах будет работать в разы быстрее. Я бы предпочёл этот вариант, потому что чаще данные в оперативку лезут, мне кажется --- а если нет, можно вручную перенаправить вывод в файл (в ТЗ этого нет, но кажется что несложно сделать).

2022-01-25 14:33 UTC, yurii-litvinov commented on bash-cli/ARCHITECTURE.md
> +* не в кавычках
Ага, разумно

2022-02-04 14:25 UTC, Atos1337 commented on bash-cli/ARCHITECTURE.md
> +* Мы никак не меняем окружение баша, в котором наше приложение вызывалось, то есть внешняя программа не будет видеть переменных, которые создавались в нашем приложении
Теперь в описании класса внешней команды прописано, что выставляем процессу окружение, совпадающее с нашим

2022-02-04 14:36 UTC, Atos1337 commented on bash-cli/ARCHITECTURE.md
> +    *   Далее создаём файлы `.cli_input`, `.cli_output`
Перешли на работу с ByteArray(Input/Output)Stream

2022-02-04 14:37 UTC, Atos1337 commented on bash-cli/ARCHITECTURE.md
> +* В поток ошибок пишем исключение, если оно вылетело и возвращаем `ReturnCode::ERROR`.
Добавил об этом в описание класса внешней команды

2022-02-04 15:01 UTC, Atos1337 commented on bash-cli/ARCHITECTURE.md
> +    *   Далее вызываем метод `Parser::parseCommands` получаем `List<String>`.
Изменили подход, см. в описание функции main

2022-02-04 15:01 UTC, Atos1337 commented on bash-cli/ARCHITECTURE.md
> +* Открываем файлы из аргументов и пишем их последовательно в поток вывода.
Видимо резолв

2022-02-05 12:03 UTC, yurii-litvinov approved these changes
Окей, всё поправлено. Зачтена

2022-02-05 12:03 UTC, yurii-litvinov commented on bash-cli/ARCHITECTURE.md
> +* Выставляем процессу окружение, совпадющее с нашим State.
```suggestion
* Выставляем процессу окружение, совпадающее с нашим State.
```

2022-03-20 15:48 UTC, merged