Grep command
Atos1337/SD-Homeworks pull request #6
Opened 2022-02-19 21:30 UTC by Atos1337

2022-02-20 18:32 UTC, Atos1337 commented
Диаграмма поправлена

2022-02-22 12:49 UTC, yurii-litvinov requested changes
По поводу диаграммы: 
- `Token [*][*]` UML не умеет, если критично показать, что это множество множеств токенов, лучше завести отдельный класс (или рисовать как `List<Token> [*]`, имея в виду библиотечный контейнер).
- Для enum-ов стоило указать их значения
- Ассоциации с enum-аим обычно не рисуют, они по смыслу типы-значения, тогда как ассоциация предполагает ссылку.
- Пачку наследников Command я бы как-то более аккуратно изобразил, как, например, в самом стандарте изображены все диаграммы: 
![image](https://user-images.githubusercontent.com/706768/155134399-42fc039b-1e58-4f7e-91a4-57b84393174f.png)

В остальном, однако, с диаграммой всё ок, но чуть поправить всё же стоит.

А ещё если пропустить число после `-A`, покрешится весь шелл. А теста на это нету.

2022-02-22 12:49 UTC, yurii-litvinov commented on bash-cli/README.md
> +Для разбора параметров была выбрана библиотека CliKt. Выбирали из неё, Apache Commons Cli и kotlinx-cli. Выбрали её, так как она наиболее Kotlin-like (используются делегирующие свойства и т.д.) и поз
В идеале ещё надо написать, почему такие кандидаты. Чтобы если вдруг завтра кто-то найдёт ещё одну либу, он понимал, пропустили вы её или она, например, имеет меньше звёзд на гитхабе и поэтому не попала в сравнение.

2022-02-22 12:49 UTC, yurii-litvinov commented on bash-cli/src/main/kotlin/ru/cli/commands/GrepCommand.kt
> +            val isInsetiveCase by option("-i").flag()
```suggestion
            val isInsensitiveCase by option("-i").flag()
```

2022-03-01 15:48 UTC, Atos1337 commented
Диаграмма исправлена, падения грепа исправлены, тест добавлен

2022-03-04 10:55 UTC, yurii-litvinov approved these changes
Значения enum-ов отделяются от имени горизонтальной чертой. Но в остальном всё так. Зачтена.

2022-03-04 10:55 UTC, yurii-litvinov commented on bash-cli/README.md
> +Для разбора параметров была выбрана библиотека CliKt. Выбирали из неё, Apache Commons Cli и kotlinx-cli, так как Apache - очень популярное семейство библиотек для Java/Kotlin, kotlinx-cli от разработ
Не-а, нет в этом методологии структурированного поиска. Каждая либа попала в список по своему какому-то критерию. С тем же успехом можно было бы написать, что Apache Commons CLI попала в обзор из-за уважения к коренным народам Северной Америки. По-хорошему должны быть описаны общие критерии и методика поиска, и уже под них — найденные библиотеки.

2022-03-20 15:50 UTC, merged